export const PLATFORM_COMMISSION_RATE = 0.05
export const DRIVER_ONLINE_COMMISSION_RATE = 0.80
export const DRIVER_COD_PLATFORM_CUT = 0.20
export const COD_DISABLE_THRESHOLD = -50000
export const COD_MAX_DISTANCE_KM = 15
export const MIN_WITHDRAW_AMOUNT = 10000
